(add-to-list 'load-path "~/.emacs.d/site-lisp/")
(add-to-list 'custom-theme-load-path "~/.emacs.d/site-lisp/")
(require 'php-mode)
(load-theme 'solarized-light t)
(require 'highlight-symbol)
(global-set-key [(control f3)] 'highlight-symbol-at-point)
(global-set-key [f3] 'highlight-symbol-next)
(global-set-key [(shift f3)] 'highlight-symbol-prev)
(global-set-key [(meta f3)] 'highlight-symbol-query-replace)
(setq viper-mode t)
;;(require 'viper)
(tool-bar-mode -1)
(set-default-font "Consolas-11")
(setq find-program "D:/cygwin/bin/find.exe")
(setq grep-command "D:/cygwin/bin/grep.exe")
(require 'highlight-indentation)
(set-face-background 'highlight-indentation-face "#e3e3d3")
